In [4]:
import numpy as np
I=np.array ([[4,3,2],[1,4,1],[3,10,4]])

print("\n Given matrix: \n", I)




eig_val,eig_vec=np.linalg.eig(I)

print("\n Eigen values: \n", eig_val) 
print("\n Eigen vectors: \n", eig_vec)

for i in range(len(eig_val)): 
    print(f"\nEigen vector for eigen value {eig_val[i]} is {eig_vec[i]}\n")



 Given matrix: 
 [[ 4  3  2]
 [ 1  4  1]
 [ 3 10  4]]

 Eigen values: 
 [8.98205672 2.12891771 0.88902557]

 Eigen vectors: 
 [[-0.49247712 -0.82039552 -0.42973429]
 [-0.26523242  0.14250681 -0.14817858]
 [-0.82892584  0.55375355  0.89071407]]

Eigen vector for eigen value 8.982056720677654 is [-0.49247712 -0.82039552 -0.42973429]


Eigen vector for eigen value 2.1289177050273396 is [-0.26523242  0.14250681 -0.14817858]


Eigen vector for eigen value 0.8890255742950096 is [-0.82892584  0.55375355  0.89071407]

